apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: preview
  installPlanApproval: Automatic
  name: cluster-logging
  source: installed-redhat-openshift-logging
  sourceNamespace: openshift-logging
