apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-logging-
  name: openshift-logging
  namespace: openshift-logging
spec:
  serviceAccount:
    metadata:
  targetNamespaces:
  - openshift-logging
